- name: install and run nginx
  hosts: web
  become: yes #root access 
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
     name: install
     state: latest
  - name: run nginx
    ansible.builtin.service:
     name: start
     state: started 
     enabled: yes

